name: Publish Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Delete existing assets (optional)
        uses: mknejp/delete-release-assets@v1
        continue-on-error: true
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          fail-if-no-release: false
          fail-if-no-assets: false

      - name: Create or Update Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest
          make_latest: true
          files: |
            *
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
